#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    configure)
	update-alternatives --remove usplash-artwork.so /usr/lib/usplash/usplash-theme-neurostvpc.so 
	#set one higher than kubuntu so kubuntu can still have standalone neurostvpc boxen too
	update-alternatives --install /usr/lib/usplash/usplash-artwork.so usplash-artwork.so /usr/lib/usplash/usplash-theme-neurostvpc.so 56
	update-initramfs -u
        ;;
esac
